# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    volumes:
      - "./:/home/appuser/app"
    profiles: ["exclude-from-up"] # Run and attach to container instead with: `docker-compose run auto-gpt`

  redis:
    image: "redis/redis-stack-server:latest"
